"""
tools/filesystem_saver.py
Tool for saving diagrams and reports to the filesystem
"""

import os
import json
from datetime import datetime
from typing import Dict, Any, Optional 
from app import config

def _sanitize_filename(filename: str) -> str:
    """Removes path characters from filename to avoid errors."""
    if not filename:
        return "unknown_source"
    base = os.path.basename(filename)
    return base.replace("/", "_").replace("\\", "_")

def save_diagram(
    mermaid_code: str,
    svg_path: Optional[str] = None,      
    metadata: Optional[Dict[str, Any]] = None  
) -> Dict[str, Any]:
    """
    Saves the final diagram (.mmd) and metadata (.json).
    """
    try:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # 1. Save Mermaid Code
        mermaid_filename = f"process_diagram_{timestamp}.mmd"
        mermaid_path = os.path.join(config.OUTPUT_DIR, mermaid_filename)
        
        cleaned_code = mermaid_code.strip()
        if cleaned_code.startswith("```mermaid"):
            cleaned_code = cleaned_code.replace("``````", "").replace("```mermaid", "").replace("```", "").strip()
        
        with open(mermaid_path, "w", encoding="utf-8") as f:
            f.write(cleaned_code)
        
        print(f"[Filesystem Saver] ✅ Mermaid code saved: {mermaid_path}")
        
        # 2. Save Metadata
        metadata_to_save = metadata or {}
        metadata_to_save.update({
            "timestamp": timestamp,
            "mermaid_file": mermaid_filename,
            "svg_file": os.path.basename(svg_path) if svg_path else None
        })
        
        metadata_filename = f"process_diagram_{timestamp}_metadata.json"
        metadata_path = os.path.join(config.OUTPUT_DIR, metadata_filename)
        
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(metadata_to_save, f, indent=2, ensure_ascii=False)
        
        print(f"[Filesystem Saver] ✅ Metadata saved: {metadata_path}")
        
        return {
            "success": True,
            "mermaid_path": mermaid_path,
            "svg_path": svg_path,
            "metadata_path": metadata_path,
            "timestamp": timestamp,
            "message": "Diagram successfully saved"
        }
        
    except Exception as e:
        error_msg = f"Error saving files: {str(e)}"
        print(f"[Filesystem Saver] ❌ {error_msg}")
        return {"success": False, "error": error_msg}


def save_report(
    mermaid_code: str,
    analysis_text: str,
    metadata: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Creates a CLEAN combined Markdown report (Text + Diagram).
    """
    try:
        raw_source = metadata.get("pdf_source", "unknown")
        # Sanitize filename
        source_name = _sanitize_filename(raw_source)
        
        ts = metadata.get("timestamp", datetime.now().strftime("%Y%m%d_%H%M%S"))
        
        report_filename = f"REPORT_{source_name}_{ts}.md"
        report_path = os.path.join(config.OUTPUT_DIR, report_filename)
        
        workflow_id = metadata.get("workflow_id", "unknown")
        
        if "```" in mermaid_code:
            clean_mermaid = mermaid_code
        else:
            clean_mermaid = f"```mermaid\n{mermaid_code}\n```"

        report_content = f"""# Process Documentation: {source_name}

## 1. Process Diagram
Here is the visual representation of the process:

{clean_mermaid}

## 2. Metadata
- **Source:** {source_name} (Original: {raw_source})
- **Workflow ID:** {workflow_id}
- **Generated at:** {ts}

---
*Generated by Process Diagram Multi-Agent System*
"""

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_content)
            
        print(f"[Filesystem Saver] ✅ Report created: {report_path}")
        
        return {
            "success": True,
            "report_path": report_path
        }

    except Exception as e:
        error_msg = f"Error creating report: {str(e)}"
        print(f"[Filesystem Saver] ❌ {error_msg}")
        return {"success": False, "error": error_msg}